pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
    }
}

include ':IconLoader'
project(':IconLoader').projectDir = new File(rootDir, 'systemui/iconloaderlib')

include ':UserTypeLib'
project(':UserTypeLib').projectDir = new File(rootDir, 'systemui/usertypelib')

// TODO: handle these dummy projects.
include ':SharedLibWrapper'
include ':NexusLauncher:Flags'
include ':frameworks:base:packages:SystemUI:SystemUISharedFlags'

