pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google {
            content {
                includeGroupByRegex("com\\.android.*")
                includeGroupByRegex("com\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
    }
}

include ':IconLoader'
project(':IconLoader').projectDir = new File(rootDir, 'systemui/iconloaderlib')

include ':SharedLibWrapper'
project(':SharedLibWrapper').projectDir = new File(rootDir, 'SharedLibWrapper')

include ':NexusLauncher.Flags'
