on:
  push:
    paths:
      - '.github/workflows/repo-sync.yml'
  pull_request:
    paths:
      - '.github/workflows/repo-sync.yml'
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch tags from upstream repository
        run: |
          git remote add upstream https://android.googlesource.com/platform/packages/apps/Launcher3
          git fetch upstream --tags
      - name: Push matching tags to the remote
        run: |
          # Match tags like android-14.0.0_r66.
          for tag in $(git tag -l "android-[0-9]*.[0-9]*.[0-9]*_r[0-9]*"); do
            # If the tag doesn't exist in the remote repository, push it.
            if ! git ls-remote --exit-code origin "refs/tags/$tag" &>/dev/null; then
              git push origin "refs/tags/$tag"
            fi
          done
