on:
  push:
    paths:
      - '.github/workflows/repo-sync.yml'
  pull_request:
    paths:
      - '.github/workflows/repo-sync.yml'
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - name: Fetch tags from upstream repository
        run: |
          git remote add upstream https://android.googlesource.com/platform/packages/apps/Launcher3
          git fetch upstream --tags
      - name: Push matching tags to the remote
        run: |
          # Match tags like android-14.0.0_r66 and push them.
          git tag | grep 'android-[0-9]*.[0-9]*.[0-9]*_r[0-9]*' | xargs --no-run-if-empty git push origin
