on:
  push:
    paths:
      - '.github/workflows/repo-sync.yml'
  pull_request:
    paths:
      - '.github/workflows/repo-sync.yml'
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Delete all remote tags
        run:
          git tag -l | xargs -n 1 git push --delete origin
