on:
  schedule:
    - cron: "0 */8 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://android.googlesource.com/platform/packages/apps/Launcher3"
          source_branch: "*"
          destination_branch: "*"
          sync_tags: "true"
          github_token: ${{ secrets.PAT_SYNC_LAUNCHER3 }}
